### ISSUE TITLE
Navigation and layout

### ISSUE THREAD

**Issue by blms** [performant-software/itsb#11]
Doesn't need to follow original exactly.

- [x] Top navigation instead of side
- [ ] Slight differences for visualizations:

Trajectories:

<img width="916" alt="Screen Shot 2022-09-26 at 4 27 57 PM" src="https://user-images.githubusercontent.com/7234006/196976328-c87b86fd-f238-487b-ac8f-4e56eaf6a6bd.png">

Floating for intersections:

<img width="1021" alt="Screen Shot 2022-09-26 at 4 30 56 PM" src="https://user-images.githubusercontent.com/7234006/196976334-7b4f0ef7-680a-45e5-be87-6ae73a370026.png">

**Comment by blms** [comment]
I'm going to label this one "question" because I'm not sure I see the utility in the floating controls for intersections; seems to take up the same amount of space. But we can bring it up with Alex when we present to him next.

**Comment by elotroalex** [comment]
The one where it doesn't float but covers the left seems better. no use for floating and it won't look that good imho.
