### ISSUE TITLE
Detail information on intersections

### ISSUE THREAD

**Issue by rsimon** [performant-software/itsb#13]
__Update: I found the [original version](https://sameboats.org/intersections/) now, so much of this is now clarified thx to issue #9__ (I still leave it here for the record).

I've been wondering about what detail information to show for an intersection place. I think this will also influence the exact API / datastructure we should be aiming for. Some thoughts...

__About place markers:__
- If there are more than two itineraries selected, should the map show only places where __all selected authors__ are in the same place? Or all places where more than one author was at the same place at the same time?
- Right now, lower likelihood results in larger dots with higher opacity. Should higher likelihood produce larger dots instead? 

__About a hover or popup component:__
Currently, there's only a debug hover tooltip. As soon as more than two authors are involved, information can become a bit complex. Would some sort of calendar heatmap (like Github's activity chart) be an option? Or is this too much detail for this project?

**Comment by rsimon** [comment]
P.S. I could imagine something like the below, with colors indicating different authors, opacity indicating different likelihoods, and overlaps shown by stacking different underlines. (Sorry for the scribbling...)

But, as I said: may be too much detail at this point. (Also because I think we'd need to build this ourselves. Solutions exist for the standard Github-style activity chart. But the "multiple underlines in one month" feature is something that likely won't exist yet.) 

![image](https://user-images.githubusercontent.com/470971/197494700-c40fe22d-fd37-4e3e-bc13-1319100f5446.png)

**Comment by rsimon** [comment]
Argh, sorry - realised too late that there is already this which we should mimick: https://sameboats.org/intersections/

So this simply lists each author's periods of presence, sorted by time, with different opacity based on likelihood. Nice & clean :-)

**Comment by blms** [comment]
I think that's a great idea for the API.

FWIW, as you can see in the original there's no way to actually filter by author—it just shows all authors. It was a natural extension for me to just use my existing author filter for it, and I think it does improve the intersections viz, but perhaps that is something we should discuss with Alex.

Also, thanks for looking into the discrepancies with the original!

**Comment by blms** [comment]
Closed by #29
