### ISSUE TITLE
AuthorSelect design

### ISSUE THREAD

**Issue by rsimon** [performant-software/itsb#34]
I'm just going over the differences between our implementation and the original app. One thing that IMO looked nice in the original design was the author list. It did not have checkboxes, but instead author names were greyed out, and colored if selected. Should we adopt the same design? (I'm a bit mixed about it TBH. On the one hand, I like the aesthetics of the original. On the other hand, having explicit checkboxes might be a good thing for UX?)

**Comment by blms** [comment]
Yes, I think I prefer it without checkboxes, but I agree in that I'm not sure how clear it is from a UX perspective. Does it communicate "selectability"? I'm definitely not the expert on that. From an accessibility perspective, I think it at least needs to have a focus style and a clear distinction between selected and deselected—and should definitely retain the checkbox inputs for screen readers, even if hidden for sighted users.

**Comment by elotroalex** [comment]
No checkboxes. Just have the words select author at the top maybe.

**Comment by blms** [comment]
Closed by #52
