### ISSUE TITLE
Selecting places in different map views

### ISSUE THREAD

**Issue by rsimon** [performant-software/itsb#35]
I looked at what happens when selecting a place in the original app design. The original app has a popup displaying the list of waypoints. (It seems to be buggy and doesn't always work. Also, it tends to get unwieldy for more than one or two waypoints.) At the moment, we only have a hover tooltip with the placename. Question is if we want to add something in our app, too?

Another, only half-related issue: when clicking on a place in the Trajectories view, this place gets globally selected, which then also causes it to be the current selection when switching to Intersections view. This seems confusing, especially because there's no visual feedback when clicking a place in the Trajectories view. I vote for making selections "local", i.e. clicks in the Trajectories view don't affect selection in the Intersections view. (Disclaimer: I'm the one who introduced this behavior in the first place, i.e. take the blame ;-)

**Comment by blms** [comment]
I was thinking about this too. For many waypoints this would definitely get unwieldy, but I also think it would be good to surface the waypoint labels somehow… I don't have a good solution for this. The only thing I can think of is introducing the third column to trajectories, but I also want to avoid that if possible 😆 maybe Alex will have an idea.

> I vote for making selections "local", i.e. clicks in the Trajectories view don't affect selection in the Intersections view. 

I agree!

**Comment by elotroalex** [comment]
I'd say leave that third column out of the Trajectories view. That view is only useful for seeing 1 or comparing 2, tops 3 people. Pop-ups should work.
