### ISSUE TITLE
GeoJSON layer of linked places

### ISSUE THREAD

**Issue by blms** [performant-software/itsb#5]
> I don't think it would cause much overhead. It would essentially be a single group-by operation, which should be quite fast. (Itineraries are lists of waypoints. You'd just need to loop through the waypoints once to get a list of distinct place IDs. Probably hardly noticable on today's hardware, even with many waypoints.) Once you have the place ID, you can map the IDs to GeoJSON features by retrieving them from the in-memory graph. Should also be very fast.

_Originally posted by @rsimon in https://github.com/performant-software/itsb/pull/4#discussion_r999839546_

**Comment by rsimon** [comment]
Note: this IMO needs to go into the [ItinerariesLayer](https://github.com/performant-software/itsb/blob/main/src/components/ItinerariesLayer/ItinerariesLayer.js) component, since this is responsible for translating the search result (=itineraries) into map-able layers for DeckGL.

**Comment by rsimon** [comment]
Looks like this on is good to close?

**Comment by blms** [comment]
Closed by #23
