### ISSUE TITLE
Migrate to sameboats.org domain

### ISSUE THREAD

**Issue by blms** [performant-software/itsb#62]
- [x] Follow [github docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)
- [x] Update GitHub Actions workflow: change this line to remove the command line arguments `-- --base "/itsb/"`:
https://github.com/performant-software/itsb/blob/58050c0a81e5a5eb5095b5eda559e0aea491417a/.github/workflows/gh-pages.yml#L39

The line in the workflow was necessary because the current site is served from  `https://performant-software.github.io/itsb/` instead of the root `https://performant-software.github.io/`. This assumes the site is meant to be served from the root `sameboats.org/`.

When successfully deployed:

- [x] Update the readme to use the new URL:
https://github.com/performant-software/itsb/blob/58050c0a81e5a5eb5095b5eda559e0aea491417a/README.md?plain=1#L7

**Comment by elotroalex** [comment]
After a whole Odyssey trying to get BlueHost to release the domain, we finally got through. The site has been succesfully migrated! And with that, we close the last ticket. Go team!! It's looking gorgeous! 🎉

**Comment by elotroalex** [comment]
For our records:

http://sameboats.org/
