### ISSUE TITLE
Map not showing on the new server

### ISSUE THREAD

**Issue by elotroalex** [performant-software/itsb#64]
Quick question. I hadn't noticed until now, that the tiles are not showing on the project in its new home. Before I start digging into the project files to figure out why, or write the server admins to see if they have some blocks that would do that, do you have any idea why this would be, Ben? I thought you might know. 

http://sameboats.org/#/trajectories

**Comment by rsimon** [comment]
Ouch - yes, the API key for the background map is locked to the (old) domain. This would be a setting that needs to be changed in the MapTiler dashboard. @blms did you set up the API key originally and have access to that specific API key?

**Comment by blms** [comment]
Oh no! Good catch, apologies for missing this in my instructions.

It's actually still using your API key @rsimon, but probably best if @elotroalex creates his own [MapTiler](https://www.maptiler.com/) account and uses that to generate an API key for this domain.

Here's the line where it's set in code:

https://github.com/performant-software/itsb/blob/4c59840d85fce387a4c11de60fa78e38f84aff31/src/pages/MapPage/MapPage.jsx#L63

**Comment by elotroalex** [comment]
Brilliant! @jamiefolsom just created a new API and sent a push request. The maps are working again! Closing this ticket.
